/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    formats: ['image/avif', 'image/webp'],
  },
  // Ensures pages are server-rendered / statically generated by default —
  // critical for AI crawlers, which generally do not execute client-side JS.
};

module.exports = nextConfig;
